[
    {
      name: 'mbox',
      value: 'session#32d7dc7d8816404fbcab52919c5725ce#1628769432|PC#32d7dc7d8816404fbcab52919c5725ce.35_0#1692012329',
      domain: '.espn.com',
      path: '/',
      expires: 1692012329,
      size: 107,
      httpOnly: false,
      secure: false,
      session: false,
      sameParty: false,
      sourceScheme: 'Secure',
      sourcePort: 443
    },
    {
      name: '_nr',
      value: '0',
      domain: 'www.espn.com',
      path: '/',
      expires: -1,
      size: 4,
      httpOnly: false,
      secure: false,
      session: true,
      sameParty: false,
      sourceScheme: 'Secure',
      sourcePort: 443
    },
    {
      name: '_chartbeat4',
      value: 't=BJM0maR43DBBFqK7JCLpKUgIwVk4&E=0&x=0&c=0.67&y=6842&w=1200',
      domain: 'www.espn.com',
      path: '/',
      expires: 1628767630,
      size: 70,
      httpOnly: false,
      secure: false,
      session: false,
      sameParty: false,
      sourceScheme: 'Secure',
      sourcePort: 443
    },
    {
      name: 'OptanonConsent',
      value: 'isIABGlobal=false&datestamp=Thu+Aug+12+2021+06%3A26%3A10+GMT-0500+(Central+Daylight+Time)&version=6.18.0&hosts=&consentId=c9f36d4f-d5f5-472d-b9aa-89b7ea7aaf83&interactionCount=1&landingPath=https%3A%2F%2Fwww.espn.com%2F&groups=C0001%3A1%2CC0003%3A1%2CC0002%3A1%2CSPD_BG%3A1%2CC0004%3A1',
      domain: '.espn.com',
      path: '/',
      expires: 1660303570,
      size: 299,
      httpOnly: false,
      secure: false,
      session: false,
      sameSite: 'Lax',
      sameParty: false,
      sourceScheme: 'Secure',
      sourcePort: 443
    },
    {
      name: 'userZip',
      value: '35476',
      domain: '.espn.com',
      path: '/',
      expires: -1,
      size: 12,
      httpOnly: false,
      secure: false,
      session: true,
      sameParty: false,
      sourceScheme: 'Secure',
      sourcePort: 443
    },
    {
      name: 'dtcAuth',
      value: 'ESPN_PLUS',
      domain: '.espn.com',
      path: '/',
      expires: 1629977170.428725,
      size: 16,
      httpOnly: false,
      secure: false,
      session: false,
      sameParty: false,
      sourceScheme: 'Secure',
      sourcePort: 443
    },
    {
      name: 'SWID',
      value: '{EA55B21B-57D7-4D03-A64A-2A3C50A10022}',
      domain: '.espn.com',
      path: '/',
      expires: 1660303570,
      size: 42,
      httpOnly: false,
      secure: false,
      session: false,
      sameParty: false,
      sourceScheme: 'Secure',
      sourcePort: 443
    },
    {
      name: 'ESPN-ONESITE.WEB-PROD.idn',
      value: '001e024bf6',
      domain: '.espn.com',
      path: '/',
      expires: -1,
      size: 35,
      httpOnly: false,
      secure: true,
      session: true,
      sameParty: false,
      sourceScheme: 'Secure',
      sourcePort: 443
    },
    {
      name: 'ESPN-ONESITE.WEB-PROD-ac',
      value: 'XUS',
      domain: '.espn.com',
      path: '/',
      expires: 2670146770,
      size: 27,
      httpOnly: false,
      secure: false,
      session: false,
      sameParty: false,
      sourceScheme: 'Secure',
      sourcePort: 443
    },
    {
      name: 'ESPN-ONESITE.WEB-PROD.token',
      value: '5=eyJhY2Nlc3NfdG9rZW4iOiJjOWRmOTYzYWU0MTc0ZWZiODEwYTUxNTc3ODVlNWU2YiIsInJlZnJlc2hfdG9rZW4iOiJlMDQ0OGEyOTRiN2Q0NzVlOTE1YWMzODEwMmUzMDZhYSIsInN3aWQiOiJ7RUE1NUIyMUItNTdENy00RDAzLUE2NEEtMkEzQzUwQTEwMDIyfSIsInR0bCI6ODY0MDAsInJlZnJlc2hfdHRsIjoxNTU1MjAwMCwiaGlnaF90cnVzdF9leHBpcmVzX2luIjoxNzk5LCJpbml0aWFsX2dyYW50X2luX2NoYWluX3RpbWUiOjE2Mjg3Njc1NjgwOTUsImlhdCI6MTYyODc2NzU2ODA5NSwiZXhwIjoxNjI4ODUzOTY4MDk1LCJyZWZyZXNoX2V4cCI6MTY0NDMxOTU2ODA5NSwiaGlnaF90cnVzdF9leHAiOjE2Mjg3NjkzNjcwOTUsInNzbyI6bnVsbCwiYXV0aGVudGljYXRvciI6ImRpc25leWlkIiwibG9naW5WYWx1ZSI6bnVsbCwiY2xpY2tiYWNrVHlwZSI6bnVsbCwic2Vzc2lvblRyYW5zZmVyS2V5IjoiMkdQL0NYK1hNYXBTSDZtbWZNTEhUdndXdDJRSllZMG5vb1ZJWEZNZUR5Z1g3bWd0d3JaMWg0amlwcEZTcXlVRk5WcXdDejNCRnB5UGJzRk5sU0FTWC9UbXhSZWxRdGNDMkpYb2k3UFRNeDBicFg0Tk55dz0iLCJjcmVhdGVkIjoiMjAyMS0wOC0xMlQxMToyNjoxMC4zMjJaIiwibGFzdENoZWNrZWQiOiIyMDIxLTA4LTEyVDExOjI2OjEwLjMyMloiLCJleHBpcmVzIjoiMjAyMS0wOC0xM1QxMToyNjoxMC4zMjJaIiwicmVmcmVzaF9leHBpcmVzIjoiMjAyMi0wMi0wOFQxMjoyNjoxMC4zMjJaIiwiYmx1ZV9jb29raWUiOm51bGx9|eyJraWQiOiJxUEhmditOL0tONE1zYnVwSE1PWWxBc0pLcWVaS1U2Mi9DZjNpSm1uOEJ6dzlwSW5xbTVzUnc9PSIsImFsZyI6IlJTMjU2In0.eyJpc3MiOiJodHRwczovL2F1dGhvcml6YXRpb24uZ28uY29tIiwic3ViIjoie0VBNTVCMjFCLTU3RDctNEQwMy1BNjRBLTJBM0M1MEExMDAyMn0iLCJhdWQiOiJFU1BOLU9ORVNJVEUuV0VCLVBST0QiLCJleHAiOjE2Mjg4NTM5NjgsImlhdCI6MTYyODc2NzU2OCwianRpIjoiQmtPQUVJVkpaeXZMYXhiT01xV29WZyIsIm5iZiI6MTYyODc2NzUwOCwiYV90eXAiOiJFWENIQU5HRV9SRUNPVkVSWV9GT1JfR1VFU1QiLCJhX2NhdCI6IkdVRVNUIiwiYXRyIjoiZGlzbmV5aWQiLCJzY29wZXMiOlsiQVVUSFpfR1VFU1RfU0VDVVJFRF9TRVNTSU9OIiwiZHRzcy1lbnRpdGxlbWVudC11c2VyLWFkbWluIl0sImNfdGlkIjoiMTMyNCIsImlnaWMiOjE2Mjg3Njc1NjgwOTUsImh0YXYiOjIsImh0ZCI6MTgwMCwicnR0bCI6MTU1NTIwMDB9.VqlOnEzlv6CF6JJkR569u0-Mmou00N2Ap__ber8nGecMVztUvS7H5pcknRBmRV31BMtEATWbTkD4gBAETh-gC7gN-WYP8lSQ_I_kHoL61_z7s_XD3aUKAVG4drij9iTt09IyeONipvejOepwIlGcE0K3yKujTVkuK3xRDApYvjjHjGfBoRs3nkSoT42pqu9b4nDqC35OMac6pUR-jWP3GtHSwgkDs7DTREtZcuIFrCpVe2Y_mpdX6fKS1rr2tLbQjwxUmwQnjSMDcm24Su9RvgMExSO2iXf-zUna1AYsW7EgYsvse8G4dFsX9dNQuG4AkE7p9jKgV9V70eYsGlveEg',
      domain: '.espn.com',
      path: '/',
      expires: 2670146770,
      size: 2033,
      httpOnly: false,
      secure: true,
      session: false,
      sameParty: false,
      sourceScheme: 'Secure',
      sourcePort: 443
    },
    {
      name: 'device_607420c4',
      value: 'a89b761e-994c-40e4-b3b2-eb6bf1626c38',
      domain: '.espn.com',
      path: '/',
      expires: 1628853968,
      size: 51,
      httpOnly: false,
      secure: true,
      session: false,
      sameParty: false,
      sourceScheme: 'Secure',
      sourcePort: 443
    },
    {
      name: 'ESPN-ONESITE.WEB-PROD.api',
      value: 'vFUbxUl0ehwzTbmPsiMWJz5DD9G3pw1VXtEhUUodkpthiOjt2yYPVHbSeg/YDp9WSNxQ0YtHfgCLgMwA5YGvZ23kB0Ok',
      domain: '.espn.com',
      path: '/',
      expires: 1628853968,
      size: 117,
      httpOnly: false,
      secure: false,
      session: false,
      sameParty: false,
      sourceScheme: 'Secure',
      sourcePort: 443
    },
    {
      name: 'espn_s2',
      value: 'AEAiVWuJuJC7h%2BdbOg3myyPPzXdMQVr2f3ulKi7pGbDzOhXX%2BX1Naj%2BwOJR96aP%2BrzQjNCi%2Bo4j4wl93NICgS10LlIxHq9O0HYsOv8tCGDBNirlWyxiCdYJbrSI5gf58thKhFn7%2BjcFu7N81RTEUqQog2ofs8ZC3DWs%2BfWtrxplc%2BQ1v8U0QUdZSsmUgAE5Kbsoa3QksD9fSkOrVEqv2OJgZJ9SEkEPyAOcvE9ghRz7UqxVkZRG9VugpLU8Agy0Z87uY8OTn8sAtEJ9I1wiJAP1qr45CnzBxqf2C8JvyVjoVPjPcZlIrr%2FsA6bF2ss9j%2F0g%3D',
      domain: '.espn.com',
      path: '/',
      expires: 2670146768,
      size: 353,
      httpOnly: false,
      secure: false,
      session: false,
      sameParty: false,
      sourceScheme: 'Secure',
      sourcePort: 443
    },
    {
      name: 'SWID_NT',
      value: '0',
      domain: '.espn.com',
      path: '/',
      expires: 1660303570,
      size: 8,
      httpOnly: false,
      secure: false,
      session: false,
      sameParty: false,
      sourceScheme: 'Secure',
      sourcePort: 443
    },
    {
      name: '_cb_ls',
      value: '1',
      domain: 'www.espn.com',
      path: '/',
      expires: 1662895530,
      size: 7,
      httpOnly: false,
      secure: false,
      session: false,
      sameParty: false,
      sourceScheme: 'Secure',
      sourcePort: 443
    },
    {
      name: '_ga',
      value: 'GA1.2.1691928956.1628767532',
      domain: '.espn.com',
      path: '/',
      expires: 1691839532,
      size: 30,
      httpOnly: false,
      secure: false,
      session: false,
      sameParty: false,
      sourceScheme: 'Secure',
      sourcePort: 443
    },
    {
      name: 'mboxEdgeCluster',
      value: '35',
      domain: '.espn.com',
      path: '/',
      expires: 1628769431,
      size: 17,
      httpOnly: false,
      secure: false,
      session: false,
      sameParty: false,
      sourceScheme: 'Secure',
      sourcePort: 443
    },
    {
      name: 's_c24_s',
      value: 'First%20Visit',
      domain: '.espn.com',
      path: '/',
      expires: 1628769328,
      size: 20,
      httpOnly: false,
      secure: false,
      session: false,
      sameParty: false,
      sourceScheme: 'Secure',
      sourcePort: 443
    },
    {
      name: 'espnCreative5688608610',
      value: 'true',
      domain: 'www.espn.com',
      path: '/',
      expires: 1628830800,
      size: 26,
      httpOnly: false,
      secure: false,
      session: false,
      sameParty: false,
      sourceScheme: 'Secure',
      sourcePort: 443
    },
    {
      name: 'block.check',
      value: 'false%7Cfalse',
      domain: '.espn.com',
      path: '/',
      expires: 1628771130,
      size: 24,
      httpOnly: false,
      secure: false,
      session: false,
      sameParty: false,
      sourceScheme: 'Secure',
      sourcePort: 443
    },
    {
      name: 'UNID',
      value: 'd064138a-1345-4abb-8467-bbf7611ef884',
      domain: '.espn.com',
      path: '/',
      expires: 1786447530,
      size: 40,
      httpOnly: false,
      secure: true,
      session: false,
      sameSite: 'None',
      sameParty: false,
      sourceScheme: 'Secure',
      sourcePort: 443
    },
    {
      name: '_cb_svref',
      value: 'null',
      domain: 'www.espn.com',
      path: '/',
      expires: 1628769330,
      size: 13,
      httpOnly: false,
      secure: false,
      session: false,
      sameParty: false,
      sourceScheme: 'Secure',
      sourcePort: 443
    },
    {
      name: '_gcl_au',
      value: '1.1.1784992014.1628767530',
      domain: '.espn.com',
      path: '/',
      expires: 1636543530,
      size: 32,
      httpOnly: false,
      secure: false,
      session: false,
      sameParty: false,
      sourceScheme: 'Secure',
      sourcePort: 443
    },
    {
      name: 'espnCreative138271411242',
      value: 'true',
      domain: 'www.espn.com',
      path: '/',
      expires: 1628830800,
      size: 28,
      httpOnly: false,
      secure: false,
      session: false,
      sameParty: false,
      sourceScheme: 'Secure',
      sourcePort: 443
    },
    {
      name: 'tveAuth',
      value: '',
      domain: '.espn.com',
      path: '/',
      expires: 1628853929,
      size: 7,
      httpOnly: false,
      secure: false,
      session: false,
      sameParty: false,
      sourceScheme: 'Secure',
      sourcePort: 443
    },
    {
      name: 'tveMVPDAuth',
      value: '',
      domain: '.espn.com',
      path: '/',
      expires: 1628853929,
      size: 11,
      httpOnly: false,
      secure: false,
      session: false,
      sameParty: false,
      sourceScheme: 'Secure',
      sourcePort: 443
    },
    {
      name: 'nol_fpid',
      value: 'ncd7ofjsekazuacyz7kwugh8bgcjf1628767529|1628767529735|1628767529735|1628767529735',
      domain: '.espn.com',
      path: '/',
      expires: 1644319529,
      size: 89,
      httpOnly: false,
      secure: false,
      session: false,
      sameSite: 'Lax',
      sameParty: false,
      sourceScheme: 'Secure',
      sourcePort: 443
    },
    {
      name: 's_ensRegion',
      value: 'ccpa',
      domain: 'www.espn.com',
      path: '/',
      expires: -1,
      size: 15,
      httpOnly: false,
      secure: false,
      session: true,
      sameParty: false,
      sourceScheme: 'Secure',
      sourcePort: 443
    },
    {
      name: 'connectionspeed',
      value: 'full',
      domain: 'www.espn.com',
      path: '/',
      expires: 1629372330.382174,
      size: 19,
      httpOnly: false,
      secure: false,
      session: false,
      sameParty: false,
      sourceScheme: 'Secure',
      sourcePort: 443
    },
    {
      name: 'IR_9070',
      value: '1628767529712%7C0%7C1628767529712%7C%7C',
      domain: '.espn.com',
      path: '/',
      expires: -1,
      size: 46,
      httpOnly: false,
      secure: false,
      session: true,
      sameParty: false,
      sourceScheme: 'Secure',
      sourcePort: 443
    },
    {
      name: '_gid',
      value: 'GA1.2.781140191.1628767532',
      domain: '.espn.com',
      path: '/',
      expires: 1628853932,
      size: 30,
      httpOnly: false,
      secure: false,
      session: false,
      sameParty: false,
      sourceScheme: 'Secure',
      sourcePort: 443
    },
    {
      name: 'IR_gbd',
      value: 'espn.com',
      domain: '.espn.com',
      path: '/',
      expires: -1,
      size: 14,
      httpOnly: false,
      secure: false,
      session: true,
      sameParty: false,
      sourceScheme: 'Secure',
      sourcePort: 443
    },
    {
      name: '_chartbeat2',
      value: '.1628767530394.1628767530394.1.Y8AqYDtQZzBDe9ToGwcg5n1JFON.1',
      domain: 'www.espn.com',
      path: '/',
      expires: 1662895530,
      size: 71,
      httpOnly: false,
      secure: false,
      session: false,
      sameParty: false,
      sourceScheme: 'Secure',
      sourcePort: 443
    },
    {
      name: '__gads',
      value: 'ID=2861082d7d3e8309:T=1628767529:S=ALNI_MZ7tFK01NWAkHIgbQMOkvWz-HqIDg',
      domain: '.espn.com',
      path: '/',
      expires: 1662463529,
      size: 75,
      httpOnly: false,
      secure: false,
      session: false,
      sameParty: false,
      sourceScheme: 'Secure',
      sourcePort: 443
    },
    {
      name: '_uetvid',
      value: 'ffb92380fb5f11ebbbe1a9b2072c3b82',
      domain: '.espn.com',
      path: '/',
      expires: 1662463529,
      size: 39,
      httpOnly: false,
      secure: false,
      session: false,
      sameParty: false,
      sourceScheme: 'Secure',
      sourcePort: 443
    },
    {
      name: '_uetsid',
      value: 'ffb8fb80fb5f11eba5919b350bda0b46',
      domain: '.espn.com',
      path: '/',
      expires: 1628853929,
      size: 39,
      httpOnly: false,
      secure: false,
      session: false,
      sameParty: false,
      sourceScheme: 'Secure',
      sourcePort: 443
    },
    {
      name: 'client_version',
      value: '4.4.0',
      domain: 'www.espn.com',
      path: '/',
      expires: -1,
      size: 19,
      httpOnly: false,
      secure: true,
      session: true,
      sameSite: 'None',
      sameParty: false,
      sourceScheme: 'Secure',
      sourcePort: 443
    },
    {
      name: 's_gpv_pn',
      value: 'espn%3Afrontpage',
      domain: '.espn.com',
      path: '/',
      expires: 1628769328,
      size: 24,
      httpOnly: false,
      secure: false,
      session: false,
      sameParty: false,
      sourceScheme: 'Secure',
      sourcePort: 443
    },
    {
      name: 'ESPN-ONESITE.WEB-PROD.ts',
      value: '2021-08-12T11:56:10.323Z',
      domain: '.espn.com',
      path: '/',
      expires: 1628769370,
      size: 48,
      httpOnly: false,
      secure: false,
      session: false,
      sameParty: false,
      sourceScheme: 'Secure',
      sourcePort: 443
    },
    {
      name: 'DS',
      value: '"bm92YW1lZGdyb3VwLmNvbTs1MTczMTE7d2hpdGVza3kgY29tbXVuaWNhdGlvbnMgbGxjLjs="',
      domain: '.espn.com',
      path: '/',
      expires: 1628777527.610894,
      size: 76,
      httpOnly: false,
      secure: false,
      session: false,
      sameParty: false,
      sourceScheme: 'Secure',
      sourcePort: 443
    },
    {
      name: '_cb',
      value: 'DQcnTZ8A6F5Tk0_f',
      domain: 'www.espn.com',
      path: '/',
      expires: 1662895530,
      size: 19,
      httpOnly: false,
      secure: false,
      session: false,
      sameParty: false,
      sourceScheme: 'Secure',
      sourcePort: 443
    },
    {
      name: 's_omni_lid',
      value: '%5B%5BB%5D%5D',
      domain: '.espn.com',
      path: '/',
      expires: -1,
      size: 23,
      httpOnly: false,
      secure: false,
      session: true,
      sameParty: false,
      sourceScheme: 'Secure',
      sourcePort: 443
    },
    {
      name: '_dcf',
      value: '1',
      domain: 'www.espn.com',
      path: '/',
      expires: -1,
      size: 5,
      httpOnly: false,
      secure: false,
      session: true,
      sameParty: false,
      sourceScheme: 'Secure',
      sourcePort: 443
    },
    {
      name: 'cookieMonster',
      value: '1',
      domain: '.www.espn.com',
      path: '/',
      expires: 1631359527,
      size: 14,
      httpOnly: false,
      secure: false,
      session: false,
      sameParty: false,
      sourceScheme: 'Secure',
      sourcePort: 443
    },
    {
      name: 'check',
      value: 'true',
      domain: '.espn.com',
      path: '/',
      expires: -1,
      size: 9,
      httpOnly: false,
      secure: false,
      session: true,
      sameParty: false,
      sourceScheme: 'Secure',
      sourcePort: 443
    },
    {
      name: '_chartbeat5',
      value: '1016|354|%2F|https%3A%2F%2Fwww.espn.com%2F|ORqLcFHhqfB-6ExcBI_DTICTeZeR||c|j4GLSClIx6UCdHGqepFdcYBuyXmM|espn.com|',
      domain: 'www.espn.com',
      path: '/',
      expires: 1628767590,
      size: 124,
      httpOnly: false,
      secure: false,
      session: false,
      sameParty: false,
      sourceScheme: 'Secure',
      sourcePort: 443
    },
    {
      name: 's_c24',
      value: '1628767528943',
      domain: '.espn.com',
      path: '/',
      expires: 1723375528,
      size: 18,
      httpOnly: false,
      secure: false,
      session: false,
      sameParty: false,
      sourceScheme: 'Secure',
      sourcePort: 443
    },
    {
      name: 'usprivacy',
      value: '1YNY',
      domain: 'www.espn.com',
      path: '/',
      expires: 1660303528,
      size: 13,
      httpOnly: false,
      secure: false,
      session: false,
      sameSite: 'Lax',
      sameParty: false,
      sourceScheme: 'Secure',
      sourcePort: 443
    },
    {
      name: 's_cc',
      value: 'true',
      domain: '.espn.com',
      path: '/',
      expires: -1,
      size: 8,
      httpOnly: false,
      secure: false,
      session: true,
      sameParty: false,
      sourceScheme: 'Secure',
      sourcePort: 443
    },
    {
      name: 'edition-view',
      value: 'espn-en-us',
      domain: 'www.espn.com',
      path: '/',
      expires: 1629372370.782827,
      size: 22,
      httpOnly: false,
      secure: false,
      session: false,
      sameParty: false,
      sourceScheme: 'Secure',
      sourcePort: 443
    },
    {
      name: 'UNID',
      value: 'd064138a-1345-4abb-8467-bbf7611ef884',
      domain: 'www.espn.com',
      path: '/',
      expires: 1786447530,
      size: 40,
      httpOnly: false,
      secure: true,
      session: false,
      sameSite: 'None',
      sameParty: false,
      sourceScheme: 'Secure',
      sourcePort: 443
    },
    {
      name: 'espnAuth',
      value: '{"swid":"{EA55B21B-57D7-4D03-A64A-2A3C50A10022}"}',
      domain: '.espn.com',
      path: '/',
      expires: 1658767570.428115,
      size: 57,
      httpOnly: false,
      secure: false,
      session: false,
      sameParty: false,
      sourceScheme: 'Secure',
      sourcePort: 443
    },
    {
      name: 'AMCV_EE0201AC512D2BE80A490D4C%40AdobeOrg',
      value: '-330454231%7CMCIDTS%7C18852%7CMCMID%7C27879980403307253294577919839385711061%7CMCAAMLH-1629372327%7C7%7CMCAAMB-1629372327%7CRKhpRz8krg2tLO6pguXWp5olkAcUniQYPHaMWWgdJ3xzPWQmdj0y%7CMCOPTOUT-1628774727s%7CNONE%7CMCAID%7CNONE%7CvVersion%7C3.1.2',
      domain: '.espn.com',
      path: '/',
      expires: 1691839527,
      size: 280,
      httpOnly: false,
      secure: false,
      session: false,
      sameParty: false,
      sourceScheme: 'Secure',
      sourcePort: 443
    },
    {
      name: '_omnicwtest',
      value: 'works',
      domain: '.espn.com',
      path: '/',
      expires: -1,
      size: 16,
      httpOnly: false,
      secure: false,
      session: true,
      sameParty: false,
      sourceScheme: 'Secure',
      sourcePort: 443
    },
    {
      name: 'edition',
      value: 'espn-en-us',
      domain: 'www.espn.com',
      path: '/',
      expires: 1629372370.78287,
      size: 17,
      httpOnly: false,
      secure: false,
      session: false,
      sameParty: false,
      sourceScheme: 'Secure',
      sourcePort: 443
    },
    {
      name: 's_sq',
      value: 'wdgespcom%252Cwdgespge%3D%2526pid%253Despn%25253Afrontpage%2526pidt%253D1%2526oid%253Dhttps%25253A%25252F%25252Fwww.espn.com%25252F%252523%2526ot%253DA',
      domain: '.espn.com',
      path: '/',
      expires: -1,
      size: 155,
      httpOnly: false,
      secure: false,
      session: true,
      sameParty: false,
      sourceScheme: 'Secure',
      sourcePort: 443
    },
    {
      name: 'client_type',
      value: 'html5',
      domain: 'www.espn.com',
      path: '/',
      expires: -1,
      size: 16,
      httpOnly: false,
      secure: true,
      session: true,
      sameSite: 'None',
      sameParty: false,
      sourceScheme: 'Secure',
      sourcePort: 443
    },
    {
      name: 'DE2',
      value: '"dXNhO2FsO25vcnRocG9ydDticm9hZGJhbmQ7NTs1OzU7NjMwOzMzLjI0Oy04Ny41OTs4NDA7MTsyMzQ5MTs2O3VzOw=="',
      domain: '.espn.com',
      path: '/',
      expires: 1628777527.610865,
      size: 97,
      httpOnly: false,
      secure: false,
      session: false,
      sameParty: false,
      sourceScheme: 'Secure',
      sourcePort: 443
    },
    {
      name: 'region',
      value: 'ccpa',
      domain: 'www.espn.com',
      path: '/',
      expires: 1629372370.782901,
      size: 10,
      httpOnly: false,
      secure: false,
      session: false,
      sameParty: false,
      sourceScheme: 'Secure',
      sourcePort: 443
    },
    {
      name: '_fbp',
      value: 'fb.1.1628767529753.404335247',
      domain: '.espn.com',
      path: '/',
      expires: 1636543530,
      size: 32,
      httpOnly: false,
      secure: false,
      session: false,
      sameParty: false,
      sourceScheme: 'Secure',
      sourcePort: 443
    },
    {
      name: 'AMCVS_EE0201AC512D2BE80A490D4C%40AdobeOrg',
      value: '1',
      domain: '.espn.com',
      path: '/',
      expires: -1,
      size: 42,
      httpOnly: false,
      secure: false,
      session: true,
      sameParty: false,
      sourceScheme: 'Secure',
      sourcePort: 443
    },
    {
      name: 's_ecid',
      value: 'MCMID%7C27879980403307253294577919839385711061',
      domain: '.espn.com',
      path: '/',
      expires: 1691839529.005616,
      size: 52,
      httpOnly: false,
      secure: false,
      session: false,
      sameParty: false,
      sourceScheme: 'Secure',
      sourcePort: 443
    },
    {
      name: 'country',
      value: 'us',
      domain: 'www.espn.com',
      path: '/',
      expires: -1,
      size: 9,
      httpOnly: false,
      secure: false,
      session: true,
      sameParty: false,
      sourceScheme: 'Secure',
      sourcePort: 443
    }
  ]